### ISSUE TITLE
Release to cover #1

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/antibot#4]
Whilst looking to see how to protect webforms I came across issue #1 and was pleased to see I wasn't the first (and also that the issue was fairly easy to address using the PR code) .  However, there has not been a release since this was committed so users are not benefitting from this new, very useful, default setting.

Please can you do a release @jenlampton ?

**Comment by jenlampton** [comment]
Here you go: https://github.com/backdrop-contrib/antibot/releases/tag/1.x-1.2.1

In general, I don't like to create a new release right away if there is only one change since the last release (unless it's a critical bugfix) but if enough time passes and nothing else comes up that needs to be fixed, I'm happy to make a release. So in short, feel free to ping me on any other issues you come across that are similar to this one!
